<?php
/** @var \TendoPay\TendopayPayment\Helper\Data $tendoHelper */
$tendoHelper = $this->helper('\TendoPay\TendopayPayment\Helper\Data');
$apiClientSecretConfigFieldValue = $tendoHelper->getConfigValues($tendoHelper->getTendoExampleInstallmentsEnabled());
$apiEnabledFieldValue = $tendoHelper->getConfigValues($tendoHelper->getAPIEnabledField());

if ($apiClientSecretConfigFieldValue === "1" && $apiEnabledFieldValue ==="1") {
    $_product = $block->getProduct();
    ?>
    <div class="tendopay__example-payment">
    <span id="tendopay_example-payment__loading" class="tendopay_example-payment__loading">
        <?= __('Loading the best price for you') ?>
        <div class="tp-loader">
            <div class="tp-loader-dots">
                <div class="tp-loader-dot"></div>
                <div class="tp-loader-dot"></div>
                <div class="tp-loader-dot"></div>
            </div>
        </div>
    </span>

        <span id="tendopay_example-payment__received" class="tendopay_example-payment__received"></span>

        <img src="<?= $tendoHelper->getTendopayLogoBlue(); ?>"
             class="tendopay__example-payment__logo">

        <br><a class="tendopay__example-payment__disclaimer"
               style="font-size: 0.8em;display: block;color: #999;">(<?= __('See if you qualify here'); ?>)</a>
    </div>
    <script>
        require(['jquery'], function ($) {
            $.ajax('<?= $tendoHelper->getUrl('tendopay/standard/examplePayment', ['price' => $_product->getFinalPrice()]) ?>')
                .done(function (data) {
                    $("#tendopay_example-payment__loading").css({display: "none"});
                    if (data && data.hasOwnProperty('data') && data.data.hasOwnProperty('response')) {
                        $("#tendopay_example-payment__received").css({display: "inline"}).html(data.data.response);
                    } else {
                        $(".tendopay__example-payment").hide();
                    }
                });

            $('body').append(
                '<div class="tendopay__popup__container" style="display: none;">' +
                '<div class="tendopay__popup__iframe-wrapper">' +
                '<div class="tendopay__popup__close"></div>' +
                '<iframe src="<?= $tendoHelper->getUrl('tendopay/standard/popupbox'); ?>" class="tendopay__popup__iframe"></iframe>' +
                '</div>' +
                '</div>');
            $('.tendopay__popup__close').click(function () {
                $('.tendopay__popup__container').toggle();
            });
            $('.tendopay__example-payment__logo, .tendopay_example-payment__received, .tendopay__example-payment__disclaimer').click(function () {
                $('.tendopay__popup__container').show();
            });
        })
    </script>
    <?php
}
?>
